name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        nim: [stable, 1.2.6]
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v3
      with:
        version: ${{ matrix.nim }}

    # workaround for https://github.com/iffy/install-nim/issues/11
    - name: Workaround SSL error with choosenim
      run: |
          curl -fO https://curl.se/ca/cacert.pem
          install cacert.pem ~/.nimble/bin
          ls ~/.nimble/bin
      shell: bash
      if: runner.os == 'Windows'

    - name: Build
      run: nimble install -y
    - name: Test
      run: nimble test -y
